### PR TITLE
Add LE Extended Advertising Report Structure

### PR DESCRIPTION
**Pull request by TechnicalUserX**
The LE Extended Advertising Report feature is added in Bluetooth 5.0.
I was not able to find a suitable structure for my custom project in the current version of BlueZ and wrote it myself. 
You can check out this structure from the link below.

https://www.bluetooth.com/specifications/specs/core-specification-5-0/

The structure is defined in the "Core Specification 5.0" PDF file, page 1213.

Sincerely.

### CODE REVIEW

**Comment by Vudentz** [comment]
Not sure why you need it though, since the HCI events are processed by the kernel, not userspace.

**Comment by TechnicalUserX** [comment]
The project which I was working on was a Bluetooth device discovery tool (more like sniffing) and I captured LE Extended Advertising Reports with my Bluetooth 5.0 adapter and I wasn't able to parse it to read address information, I basically couldn't find a structure to cast the raw data. Then I figured it out by using Wireshark that it was actually Extended Advertising. Since this structure is not in the library, I implemented it myself to my project by reading the bytes from Wireshark and reading the Core Specification PDF.

And now, I just wanted to share it with you. That's all. :)

**Comment by Vudentz** [comment]
We do have such a tool called btmon, it actually has all the HCI definition in monitor/bt.h

**Comment by TechnicalUserX** [comment]
Oh, you are right, I totally missed that header file, thank you for indicating it.

**Pull request closed without merging**
